
class user:
    def __init__(self, handle):
        self.Handle = handle
        self.Political_Preference = 0
        self.Ambitious  = 0
        self.Adventure = 0
        self.Humor  = 0
        self.Confidence = 0
        self.Rude = 0
        self.Social = 0
        self.Food = 0
        self.Arts = 0
        self.Sports = 0
        self.Music = 0
        self.Movies = 0
        self.Nerdist = 0
        self.Introvert = 0
        self.Strongman = 0
        self.Social_Justice  = 0
        self.Cars = 0
        self.Philosophical  = 0
        self.Feeler = 0
        self.Judgmental  = 0
        self.Sexual = 0
        self.Fashion = 0
        self.Books = 0
        self.TV_shows = 0
        self.Celebrities = 0
        self.Sarcasm = 0
